/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-03-2011
 * 
 * XDoclet definition:
 * @struts.form name="sloginForm"
 */
public class SloginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sid property */
	private String sid;

	/** sname property */
	private String sname;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sid.
	 * @return String
	 */
	public String getSid() {
		return sid;
	}

	/** 
	 * Set the sid.
	 * @param sid The sid to set
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/** 
	 * Returns the sname.
	 * @return String
	 */
	public String getSname() {
		return sname;
	}

	/** 
	 * Set the sname.
	 * @param sname The sname to set
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}