/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.struts.action;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.qianyu.struts.form.DemoForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-27-2011
 * 
 * XDoclet definition:
 * @struts.action path="/demo" name="demoForm" input="/form/demo.jsp" scope="request" validate="true"
 */
public class DemoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DemoForm demoForm = (DemoForm) form;// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("GBK");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//System.out.println("**性别"+demoForm.getSex());
		//System.out.println("**城市"+demoForm.getCity());
		/*System.out.println("**水果");
		for(int i=0;i<demoForm.getFruit().length;i++){
			System.out.println("   |-"+demoForm.getFruit()[i]);		
		}*/
		System.out.println(demoForm.getSex());
		return null;
	}
}