/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;
import org.qianyu.struts.form.ExampleForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-02-2011
 * 
 * XDoclet definition:
 * @struts.action path="/example" name="exampleForm" input="/form/example.jsp" scope="request" validate="true"
 */
public class ExampleAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//ExampleForm exampleForm = (ExampleForm) form;// TODO Auto-generated method stub
		DynaActionForm hitForm =(DynaActionForm)form ;
		//System.out.println(exampleForm.getName());
		System.out.println(hitForm.getString("name"));
		System.out.println(hitForm.getString("password"));
		return null;
	}
}