/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.qianyu.struts.form.FirstForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/first" name="firstForm" input="/form/first.jsp" scope="request" validate="true"
 */
public class FirstAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FirstForm firstForm = (FirstForm) form;// TODO Auto-generated method stub
		this.saveToken(request);
		return mapping.findForward("insert");
	}
}