/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.qianyu.struts.form.NoteForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/note" name="noteForm" input="/form/note.jsp" scope="request" validate="true"
 */
public class NoteAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NoteForm noteForm = (NoteForm) form;// TODO Auto-generated method stub
		//≈–∂œtoken”––ß∑Ò
		if(this.isTokenValid(request)){
			System.out.println(noteForm.getTitle());
			System.out.println(noteForm.getAuthor());
			System.out.println(noteForm.getContent());
			this.resetToken(request);
		}else{
			ActionMessages errors=new ActionMessages();
			errors.add("token", new ActionMessage("token"));
			this.saveErrors(request, errors);
			return mapping.getInputForward();
		}
		
		return null;
	}
}