/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.dtree.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-15-2011
 * 
 * XDoclet definition:
 * @struts.form name="insertForm"
 */
public class InsertForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** plevel property */
	private Integer plevel;

	/** outadd property */
	private String outadd;

	/** outsource property */
	private String outsource;

	/** name property */
	private String name;

	/** property property */
	private String property;

	/** clevel property */
	private Integer clevel;

	/** produce property */
	private String produce;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the plevel.
	 * @return Integer
	 */
	public Integer getPlevel() {
		return plevel;
	}

	/** 
	 * Set the plevel.
	 * @param plevel The plevel to set
	 */
	public void setPlevel(Integer plevel) {
		this.plevel = plevel;
	}

	/** 
	 * Returns the outadd.
	 * @return String
	 */
	public String getOutadd() {
		return outadd;
	}

	/** 
	 * Set the outadd.
	 * @param outadd The outadd to set
	 */
	public void setOutadd(String outadd) {
		this.outadd = outadd;
	}

	/** 
	 * Returns the outsource.
	 * @return String
	 */
	public String getOutsource() {
		return outsource;
	}

	/** 
	 * Set the outsource.
	 * @param outsource The outsource to set
	 */
	public void setOutsource(String outsource) {
		this.outsource = outsource;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the property.
	 * @return String
	 */
	public String getProperty() {
		return property;
	}

	/** 
	 * Set the property.
	 * @param property The property to set
	 */
	public void setProperty(String property) {
		this.property = property;
	}

	/** 
	 * Returns the clevel.
	 * @return Integer
	 */
	public Integer getClevel() {
		return clevel;
	}

	/** 
	 * Set the clevel.
	 * @param clevel The clevel to set
	 */
	public void setClevel(Integer clevel) {
		this.clevel = clevel;
	}

	/** 
	 * Returns the produce.
	 * @return String
	 */
	public String getProduce() {
		return produce;
	}

	/** 
	 * Set the produce.
	 * @param produce The produce to set
	 */
	public void setProduce(String produce) {
		this.produce = produce;
	}
}