/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.qianyu.dtree.struts.action;



import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.qianyu.dtree.factory.DAOFactory;
import org.qianyu.dtree.pojo.Item;
import org.qianyu.dtree.struts.form.InsertForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-15-2011
 * 
 * XDoclet definition:
 * @struts.action path="/insert" name="insertForm" input="/form/insert.jsp" scope="request" validate="true"
 */
public class InsertAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertForm insertForm = (InsertForm) form;// TODO Auto-generated method stub
		int id = 0;
		boolean flag=false;
		try{
			id=insertForm.getClevel();
			DAOFactory.getItemDAOInstance().delete(id);
			DAOFactory.getItemDAOInstance().deleteByPlevel(id);
			flag=true;
		}catch(Exception e){
			e.printStackTrace();
		}
		request.setAttribute("flag", new Boolean(flag));
		return mapping.findForward("deletedo");
	}
	
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertForm insertForm = (InsertForm) form;// TODO Auto-generated method stub
		Item item=new Item();
		item.setClevel(insertForm.getClevel());
		item.setPlevel(insertForm.getPlevel());
		item.setName(insertForm.getName());
		item.setProperty(insertForm.getProperty());
		item.setProduce(0);
		item.setOutadd(1);
		item.setOutsource(0);
		boolean flag=false;
		try{
			DAOFactory.getItemDAOInstance().insert(item);
			flag=true;
		}catch(Exception e){
			e.printStackTrace();
		}
		request.setAttribute("flag", new Boolean(flag));
		return mapping.findForward("insertdo");
	}
	
	public ActionForward selectid(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertForm insertForm = (InsertForm) form;// TODO Auto-generated method stub
		int id=0;
		try{
			id=insertForm.getClevel();
			request.setAttribute("item", DAOFactory.getItemDAOInstance().queryById(id));
		}catch(Exception e){
			e.printStackTrace();
		}
		return mapping.findForward("update");
	}
	
	public ActionForward queryid(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertForm insertForm = (InsertForm) form;// TODO Auto-generated method stub
		int id=0;
		try{
			id=insertForm.getClevel();
			request.setAttribute("item_in", DAOFactory.getItemDAOInstance().queryById(id));
			List<?> all=DAOFactory.getItemDAOInstance().queryAll();
			request.setAttribute("all",all);
		}catch(Exception e){
			e.printStackTrace();
		}
		return mapping.findForward("insert");
	}
	
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertForm insertForm = (InsertForm) form;// TODO Auto-generated method stub
		int id=0;
		Item item= new Item();
		try{
			id=insertForm.getClevel();		
		}catch(Exception e){
			e.printStackTrace();
		}		
		item.setClevel(id);
		item.setPlevel(insertForm.getPlevel());
		item.setName(insertForm.getName());
		item.setProperty(insertForm.getProperty());
		item.setOutadd(1);
		item.setProduce(0);
		item.setOutsource(0);
		boolean flag=false;
		try{
			DAOFactory.getItemDAOInstance().update(item);
			flag=true;
		}catch(Exception e){
			e.printStackTrace();
		}
		request.setAttribute("flag", new Boolean(flag));
		return mapping.findForward("updatedo");
	}
}